spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  application:
    name: quiz-base
  profiles:
    active: heroku
